# Generated by Django 2.2.14 on 2023-04-25 16:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('lower', models.FloatField(null=True)),
                ('upper', models.FloatField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lower__isnull', True), ('upper__isnull', False)), models.Q(('lower__isnull', False), ('upper__isnull', True)), models.Q(models.Q(('lower__isnull', False), ('upper__isnull', False)), ('upper__gte', django.db.models.expressions.F('lower')), models.Q(('upper__gte', 0), ('lower__gte', 0))), _connector='OR'), name='%(app_label)s_%(class)s_positive_lower_and_or_higher'),
        ),
    ]
